### ISSUE TITLE
AssertionError [ERR_ASSERTION]: 0.3 === 1

### ISSUE THREAD

**Issue by mellema** [artilleryio/artillery#1365]
I'm running Artillery load test scripts in Jenkins using a Docker image. I've been using v1.6.2 but it doesn't have metrics-by-endpoint in it so I'd like to switch to :latest. When I run this command in my Jenkins pipeline:

`/home/node/artillery/bin/run run -t https://api.staging.parsable.net/ --config motherConfig.yml --overrides '{"config": {"phases": [{"duration": 360, "arrivalRate": 0.3, "rampTo": 0.3}]}}' jobroles.yml'
`
I get the error "AssertionError [ERR_ASSERTION]: 0.3 === 1". I'm assuming this is a problem with one of my overRides, but it worked fine in v1.6.2 so not sure what the issue is. 

Also, my v1.6.2 code did not run in :latest at first. I examined the Dockerfile and saw that ENTRYPOINT "/home/node/artillery/bin/artillery" had changed to "/home/node/artillery/bin/run" in the :latest version so I changed that in my sh command, not sure if that's correct.

**Comment by hassy** [comment]
hi @mellema 👋 

I'll need to check what setting a float like `0.3` for values of `arrivalRate` or `rampTo` did in v1.6.2. The error you're seeing is due to Artillery now expecting those values to be whole numbers.

The entrypoint did change in the most recent release, changing it to `/home/node/artillery/bin/run` is the right thing to do.

**Comment by mellema** [comment]
OK thanks for the clarification. I'm upgrading from 1.6.2 and I'm finding other issues but I'll open a new issue to discuss
