### ISSUE TITLE
Docker image for v2.0.0-28 not published

### ISSUE THREAD

**Issue by nbrown-cmx** [artilleryio/artillery#1787]
For some reason during the latest release v2.0.0-28, an updated docker image was not provided (https://hub.docker.com/r/artilleryio/artillery/tags). The last docker image was updated for v2.0.0-27 and many past releases were updated at the same date as the release of the code. Was a manual step missed or is something blocking the image from being released this time?

Our team is looking forward to using the bug fix for aws:lambda VPC security groups and subnet ids.

**Comment by hassy** [comment]
hi @nbrown-cmx 👋 the image for v2.0.0-28 is indeed missing. Our Docker images are built & published from our CI pipeline, but the job didn't run for that release because Dockerhub credentials had been disabled earlier this month due to a [CircleCI security breach](https://circleci.com/blog/jan-4-2023-incident-report/)

It's back now, and the image for [Artillery `v2.0.0-29`](https://github.com/artilleryio/artillery/releases/tag/artillery-2.0.0-29) is available: https://hub.docker.com/layers/artilleryio/artillery/2.0.0-29/images/sha256-119ff812d61f23ba6da14ab7d0ed7c1bafa8fb0e54e189d1621f156b28f9d7a7?context=explore

**Comment by nbrown-cmx** [comment]
That'll work. Thanks for the quick turn around.
