### ISSUE TITLE
plugin playwright not working

### ISSUE THREAD

**Issue by jose-JSQ** [artilleryio/artillery#2160]
Per artillery documentation:
https://www.artillery.io/docs/reference/engines/playwright
and
https://www.artillery.io/docs/reference/engines/playwright
I am trying to use plugin playwright so I can get metrics by page visited. However, I am getting the following error when running test:
Plugin playwright specified but module artillery-plugin-playwright could not be found (MODULE_NOT_FOUND)
There is no such package in https://www.npmjs.com/

VERSION INFO:
Artillery: 2.0.0-36
Node.js:   v18.16.1
OS:        darwin

Running this command: 
artillery run <test>

I expected to see this happen:
results metrics by page visited

Instead, this happened:

WARNING: Could not load plugin: playwright warn
WARNING: Plugin playwright specified but module artillery-plugin-playwright could not be found (MODULE_NOT_FOUND) warn

metrics  FCP,LCP are shown for login page, not other pages
Only CLS and TTFB is shown for page that I am looking metrics.

I assume this is happening because of PLUGIN

**Comment by InesNi** [comment]
Hello @jose-JSQ 👋🏻 ,

I believe you are getting the `plugin` warning because you are specifying `playwright` as a plugin. `Playwright` is an `engine` not a `plugin`, as per the documentation: https://www.artillery.io/docs/reference/engines/playwright#usage

You should specify it in the config like this:
```yaml
config:
  # Load the Playwright engine:
  engines:
    playwright: {}
```

Just remove any `plugin: playwright` from your config that you might have, and the warning should go away.

**Comment by jose-JSQ** [comment]
Hi @InesNi, thanks for reply. 
I did remove the plugin part. However, what I am trying to get from the test is metrics FCP, LCP by page visited.
For instance, from artillery documentation, page.goto("https://www.artillery.io/"); and page.click("text=Cloud"); give as a result metrics browser.oage.FCP and LCP for "artillery.io" as well as "artillery.io/cloud".
In my case, it does provide FCP and LCP for login page but not for the next page. I only get CLS and TTFB.
Any insight in how to get all metrics for each page?

**Comment by bernardobridge** [comment]
Hey @jose-JSQ,

Certain Web Vital metrics can be a little flakey due to Playwright interacting too fast with the page (for example, see this issue: https://github.com/GoogleChrome/web-vitals/issues/180). 

For that reason, you may want to add a little bit of interactivity in the test on the page you're going to, so there's enough time for the web vitals script to capture metrics, otherwise Playwright may simply close before there was time for those metrics to be reported.

**Comment by jose-JSQ** [comment]
Thanks for the reply @bernardobridge.
In order to make it work and get all metrics, I had to "page.visit" my second page after login. Clicking a tab after login was not giving the metrics, not even adding some more interactions.

**Comment by jose-JSQ** [comment]
Closing ticket since I resolved in previous comment.
