### ISSUE TITLE
Problem with implementing HTTP Actions Mixed with Socket.io

### ISSUE THREAD

**Issue by kwolekgrzesiek** [artilleryio/artillery#2299]
Version info: 
```
v2.0.0-38
```

Running this command: 
```
artillery run script.yml
```

I am experiencing an issue with the Artillery package where mixing in HTTP actions with Socket.io, as outlined in the documentation, isn't working as intended.

This functionality is detailed in the Artillery documentation, specifically in the Socket.io engine section, which discusses mixing in HTTP actions. You can find the relevant documentation here: [Mixing in HTTP Actions - Artillery Docs](https://www.artillery.io/docs/reference/engines/socketio#mixing-in-http-actions).

Additionally, the Artillery documentation provides a playground example demonstrating this functionality, and it appears to fail there as well. You can view it here for reference: [Artillery Playground Example](https://play.artillery.io/?s=98165442-de12-4f64-9cce-95aeba673c38&hR=true).

When I tried debugging it locally, it seemed that HTTP requests did not fire when the 'engine: socketio' was specified.

<img width="1385" alt="image" src="https://github.com/artilleryio/artillery/assets/29139697/47f64ce8-ae5b-476d-8964-2c44a728ef0b">

**Comment by bernardobridge** [comment]
Hi @kwolekgrzesiek 👋 Thanks for reporting the issue.

I believe the issue is actually with the lab's socketio server, not with Artillery itself. We'll take a look at that soon.

However, Artillery CLI should be working correctly with HTTP and Socket.io. I actually recently fixed one of our examples with that, so perhaps you can use that to guide you? https://github.com/artilleryio/artillery/tree/main/examples/http-socketio-server

Please do let us know if that's not working, though!

**Comment by kwolekgrzesiek** [comment]
@bernardobridge Yep, and it was also a problem with my local server 🫠
