### ISSUE TITLE
Lambda unzipped size too large

### ISSUE THREAD

**Issue by jdelaune** [artilleryio/artillery#2551]
Version info: 2.0.7
```
Artillery: 2.0.7
Node.js:   v20.10.0
OS:        darwin
```

Running this command: 
```
npx artillery run-lambda -e mysql8 --region us-east-1 ./scenarios/booking_flow.yml
```

I expected to see this happen:

The test to run.

Instead, this happened:

`InvalidParameterValueException: Unzipped size must be smaller than 262144000 bytes`

My package dependencies are only:

```
    "dependencies": {
        "artillery": "^2.0.6",
        "artillery-engine-playwright": "^1.4.0",
        "playwright": "^1.41.0"
    }
```

So nothing out of the ordinary.

**Comment by bernardobridge** [comment]
Hello @jdelaune 👋 . 

First, a couple of notes:
- Please don't include `artillery-engine-playwright` as a dependency. Artillery itself bundles it, so it's unneeded.
- `Playwright` is also not needed, and in fact we recommend not installing it as a dependency unless you pin to the specific version Artillery is using, since it installs specific browser versions for compatibility.

But the actual reason this is happening is likely due to the Lambda code which detects dependencies is picking up your `package.json` and installing everything there, so it's installing artillery again, etc.

To prevent this, can you try to ensurethat the `scenario` you're trying to run is not located in the same place where the package.json is.

---

Also, just an aside, but Playwright is not compatible with running tests on Lambda. If you need to run Playwright tests in distributed mode, please use Fargate.

**Comment by jdelaune** [comment]
If it's not support then I won't continue with my efforts. Thanks :)

**Comment by bernardobridge** [comment]
Hi @jdelaune , just out of curiosity, anything preventing you from using `Fargate` instead of `Lambda`? It works in a very similar way to how Lambda would, but the support is much more enhanced from our side. Thanks!

**Comment by jdelaune** [comment]
No. I'm using `Fargate` now. Just thought `Lambda` would just less heavy hitting which is why I was trying it first.
