### ISSUE TITLE
Artillery Cloud - Free Unresponsive on Mac Chrome

### ISSUE THREAD

**Issue by jbergeronjr** [artilleryio/artillery#3229]
Version info: 
```
2.0.14
```

Running this command: 
```
Artillery Cloud in Chrome Browser: https://app.artillery.io/load-tests/***
```

I expected to see this happen:

Test Loads. Metrics load. Can view Route details, response times, charts, etc.

Instead, this happened:

In Chrome and firefox, the page becomes unresponsive. Can't actually use anything in the browser. I don't want to put the test id in for security reasons.

Files being used:
```
N/a
```

**Comment by manfromanotherland** [comment]
Is this happening for a specific test or for each of your test runs? Could you share the test ID with us so we can look into it? Thanks!

**Comment by jbergeronjr** [comment]
@manfromanotherland Every test run is running like this. tghej_jy8tqbe5h94nwhzqmzpxkaznpz68p_ypmk

**Comment by manfromanotherland** [comment]
@jbergeronjr the browser is hanging because the test run you shared has more than 8000 URLs. We have pushed an quick fix that should help with performance a bit, and will continue to work on performance improvements for tests like that.

In the meantime, you can use [this option](https://www.artillery.io/docs/reference/extensions/metrics-by-endpoint#useonlyrequestnames-example) to reduce the number of URLs reported on your test runs.

Thanks again for letting us know!

**Comment by jbergeronjr** [comment]
Perfect! Thanks so much. Honestly, I would suggest making that default initially. Especially if people are dynamically testing different url params.
