### ISSUE TITLE
CSV-related regression in 1.6.0-26

### ISSUE THREAD

**Issue by hassy** [artilleryio/artillery#588]
Can be reproduced with:

- https://gist.github.com/kirksl/a3f9b4a846ed2f77973831534502044b
- https://gist.github.com/kirksl/04af538299bd824baacab2d9e914a311

Original issue description: https://github.com/artilleryio/artillery-plugin-expect/pull/1#issuecomment-443301150

**Comment by hassy** [comment]
@kirksl that script seems to run fine for me on `v1.6.0-26`. So it's either somehow Windows-specific or is triggered by the requests being made (I commented out the actual requests), which would be strange since the code that throws an exception runs before any requests are made.

**Comment by kirksl** [comment]
@hassy could you send me a gist of what you tried.  i'm still seeing the same issue.

**Comment by rajeshja** [comment]
I'm seeing the following error for a non-empty csv file:

    Invalid Option: from_line must be a positive integer greater than 0, got 0

at `csv-parse/lib/index.js`. This is because the CSV line numbers are expect to start at 1, not 0.

Analyzing further leads me to this line in `artillery/lib/commands/run.js`:

    from_line: typeof payloadSpec.skipHeader === true ? 1 : 0,

Given that csv-parse expects from_line to be 1 or more, shouldn't the above be changed to the following?

    from_line: typeof payloadSpec.skipHeader === true ? 2 : 1,

Sorry if commenting on the wrong issue, but what I'm seeing does seem to be a regression from 1.6.0-25 to 1.6.0-26.

**Comment by rajeshja** [comment]
FYI, changing `2 : 1` to `1 : 0` does seem to work for me.

**Comment by rajeshja** [comment]
From what I can tell, this regression was introduced on Dec 31, with the update of csv-parse to 4.3.0. The from_line parameter should always have been `2 : 1` but this was exposed only with 4.3.0 of the library because of some validation refinements.

I'll raise a new issue for this problem.

**Comment by rajeshja** [comment]
Created #622
