### ISSUE TITLE
[Feature] Random branching flows

### ISSUE THREAD

**Issue by andykais** [artilleryio/artillery#712]
Hi all, I have spent some time reading through your docs and I see a lot of use cases artillery can handle! However, there are some heavier realistic use cases that it cannot handle.

In the case of our team, we need to model our api for users inside a game. This means there isn't one flow that they follow. Instead, they may enter a match, do single player, change player settings, etc. This all needs to be incorporated into our load test for a single user, and that same user should be able to do actions multiple times.

For a small vis:
a 'user' would need to pick between one of these blocks and re-pick once their block ended
```
+---------------+ +-------------+ +-----------------+
| single player | | multiplayer | | player settings |
|      40%      | |     50%     | |      10%        |
+---------------+ +-------------+ +-----------------+
```

a single block might look like this (e.g. more branching flows):
```
    mulitplayer
        |
     /      \
    /        \
  1 v 1   free for all
  70%        30%
   |          |
start match   ...
   |
think 60
   |
end match

```

As far as I can tell, something like this is not possible in artillery. Is this something that has been discussed before, or is this the first time it has been brought up

**Comment by hassy** [comment]
One way to do it could be by extracting common sub-flows and then using YAML anchors and references to create scenarios containing different combinations of those sub-flows. E.g.:

1. Scenario 1: 1v1 followed by a free-for-all
2. Scenario 2: 1v1, another 1v1, another 1v1
3. Scenario 3: free-for-all, followed by a 1v1

You can then assign weights to those scenarios, so that scenario 1 is picked by 50% of all users, and scenario 2 and scenario 3 each are picked by 25% of all users.

Not *exactly* what you're after, but should allow you to achieve pretty much the same result.

**Comment by vegerot** [comment]
You've got to be kidding me.  What @hassy recommended was cool, and I did not know you could do that with YML but that's in no way a scalable solution for branching sub flows.
